### ISSUE TITLE
Unable to train word2vec on my dataset

### ISSUE THREAD

**Issue by KhondokerIslam** [sagorbrur/bnlp#13]
Given the .txt file path, vector_name and model_name, I do not get any output on word2vec when training with my own dataset. Hoping for a quick fix.

**Comment by sagorbrur** [comment]
Hi,
Thanks for your issue. 
There is  a simple less information in `README.md` or documentation. 
Just change this line: 
```py
bwv = Bengali_Word2Vec()
```
to 
```py
bwv = Bengali_Word2Vec(True)
```
Here `True` is a parameter called `is_train`. 
Hope it will solve your problem. Let us know if it works or not. 
regards

**Comment by KhondokerIslam** [comment]
It works good now. Thanks
