### ISSUE TITLE
NER, POS tags are not well documented

### ISSUE THREAD

**Issue by soumayan** [sagorbrur/bnlp#18]
Hey can you please list all NER and POS tags (specifically POS) and also what tag defines what?
It will be very much helpful for all the users.

**Comment by sohel-sec** [comment]
Currently i am facing "word embedding" (to extract the hidden state)
problem using BERT.  I have got memory limit crashed problem.

If you help me, i will appreciate it.

**Comment by sagorbrur** [comment]
Hi @soumayan ,
thank you for your suggestion. I will add NER and POS tags list soon.
regards

**Comment by sbiales** [comment]
Hi, I may just be missing it, but I am trying to use the POS tagging with the pretrained model, but I am not certain what POS tag convention this follows, is there a list of POS tags or explanation of the tagging scheme somewhere? Thanks!

**Comment by sagorbrur** [comment]
Hi @sbiales 
sorry for the late reply.
The datasets I have used is this datasets [https://github.com/abhishekgupta92/bangla_pos_tagger](https://github.com/abhishekgupta92/bangla_pos_tagger)
Unfortunately, I also don't have details about the convention. It's a straightforward data conversion and training approach I have followed. You can separate the unique POS tag and find the meaning by searching or can ask in the datasets repo. This is the minor suggestions I can provide.
