### ISSUE TITLE
pip installation fails in python 3.8

### ISSUE THREAD

**Issue by faruk-ahmad** [sagorbrur/bnlp#2]
Tried to install the library using python 3.8. It fails with the following message.
[<a href="https://ibb.co/47PMZv2"><img src="https://i.ibb.co/pxJZvVQ/Screenshot-from-2019-11-23-20-07-05.png" alt="Screenshot-from-2019-11-23-20-07-05" border="0"></a>](url)

**Comment by sagorbrur** [comment]
Vai it's working for python <=3.6 because I built it in 3.6. I will try to build it in other version too.

**Comment by faruk-ahmad** [comment]
> Vai it's working for python <=3.6 because I built it in 3.6. I will try to build it in other version too.

I saw the statement **python_requires='>=3.6'** in setup.py and tried with python 3.8

**Comment by sagorbrur** [comment]
modifying it with python_requires=3.6. Hope misunderstanding will be solved vai. :D
