### ISSUE TITLE
NER Dataset details missing

### ISSUE THREAD

**Issue by KGtk-git** [sagorbrur/bnlp#21]
The NER dataset is pointed to https://github.com/MISabic/NER-Bangla-Dataset however this link returns 404-Page not found.
Would you pls add details of the dataset used for training for NER task!
It would be great, if you could share the dataset as well.

**Comment by sagorbrur** [comment]
Hi @KGtk-git ,
Thanks for raising this concern.
Unfortunately, NER Bangla Dataset author removed that repo.
Don't know why. I will send a query mail to the author and let you know the details here.
regards

**Comment by KGtk-git** [comment]
Thanks a lot for the response.
I'm doing research with Bengali NLP and NER, and while looking at various models, I got curious to know - if you are also the author for https://huggingface.co/sagorsarker/bangla-bert-base as well, and likewise I am wondering if the BNLP and bangla-bert-base  are same models!

**Comment by sagorbrur** [comment]
yes, I am the author of the huggingface bangla bert base model.
But BNLP and bangla-bert are not same. you can find bangla-bert model details here  https://github.com/sagorbrur/bangla-bert
I tried to make BNLP as simple as possible. So no deep learning model used herein BNLP.
regards

**Comment by KGtk-git** [comment]
Oh, great to hear this. Thanks for the awesome contributions. I have checked Bangla-bert details. But, not sure of the BNLP. It would be great if you share some details as in which model is used here and the likes.

**Comment by sagorbrur** [comment]
check this preprint https://arxiv.org/pdf/2102.00405.pdf 
hope you will get details about BNLP
regards

**Comment by KGtk-git** [comment]
This is very help. Thank you very much.
I will wait for your further updates on the NER data set.

**Comment by sagorbrur** [comment]
Hi @KGtk-git,
The link you reported has activated again.
Thanks for your patience.
I am closing this issue now. 
regards
