### ISSUE TITLE
punkt not found. downloading...

### ISSUE THREAD

**Issue by bipulcn** [sagorbrur/bnlp#23]
On php shell-exec execution when it calls bnlp.corpus 
shows "punkt not found. downloading..."

Can not find out why?

**Comment by sagorbrur** [comment]
Hello @bipulcn ,
This message only shows when there is no "punkt" corpus package found in nltk.
according to the codes, after showing this message it will automatically download that corpus package from nltk.
and next time you run this code again, it won't show this warning again.
Hope that helps.

**Comment by bipulcn** [comment]
thank you for your reply. It was working on the command line. letter I found the problem why it's showing this error.
Its because nltk library was downloaded on 
```
/root/nltk_data
```
but it is supposed to be at
```
/usr/share/nltk_data
```
as I changed it and it works fine
