### ISSUE TITLE
"get_sentence_similarity" is not working

### ISSUE THREAD

**Issue by DevDaring** [sagorbrur/bnlp#30]
I had tried to run the command "get_sentence_similarity" but it did not work. It is throwing this error
FileNotFoundError: [Errno 2] No such file or directory: 'model\\export.pkl'
I have tried to download all pretrained model but that also throwing error.
download_models() generates following error.
zipfile.BadZipFile: File is not a zip file
Please update the documentation how to use "get_sentence_similarity" .

**Comment by sagorbrur** [comment]
Hi @DevDaring 
Maybe you raise the issue in the wrong repository. 
As far I understand you mean the "bnlm" library. 
Someone also raises similar issues. 
you can download the model manually using the drive path and try with the model. 
It's an issue with google drive download scripts. I might need to update the script.
I am hoping it will work. 
As it's not that repository I am closing it here.
