### ISSUE TITLE
Unable to use Bangla Glove Vecotrs

### ISSUE THREAD

**Issue by saadat-r-ahmed** [sagorbrur/bnlp#31]
Hi, Recently I tried to use the Bangla Glove vectors but unfortunately was unable to use it for some errors. Could you please have a look into it? I tried using both the HuggingFace distribution through API and also downloaded the zip file(does not unzip).
<img width="723" alt="image" src="https://github.com/sagorbrur/bnlp/assets/63824872/2422577b-4b4b-40bb-9a2b-c303531b8bde">
`Archive:  bnglove.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of bnglove.zip or
        bnglove.zip.zip, and cannot find bnglove.zip.ZIP, period.`

**Comment by sagorbrur** [comment]
Hi @saadat-r-ahmed,
It might be a problem with your download vector path. Recheck your vector path.
Keep your vector in your working directory or change the vector path according to its absolute path.
