### ISSUE TITLE
Unable to get the vocabulary of Word2Vec in  bwv = BengaliWord2Vec()

### ISSUE THREAD

**Issue by hegdekasha** [sagorbrur/bnlp#37]
I am Using bwv = BengaliWord2Vec(). But unable to get the vocabulary length.

**Comment by sagorbrur** [comment]
Hi @hegdekasha,
You can get the vocab length by the following code
`len(bwv.model.wv)`

`BengaliWord2Vec()` contains the model as a class constructor variable. When you call `bwv.model` it will return the word2vec model just like the Gensim load model.

**Comment by hegdekasha** [comment]
Thank you so much. You made my day. Thank you




*Regards*
Asha Hegde
Research Scholar
Department of Computer Science
Mangalore University

**Comment by hegdekasha** [comment]
I am having one more issue in loading bft = BengaliFasttext(). I am getting
error like " NameError: name 'fasttext' is not defined" Could help me
please to resolve this?



*Regards*
Asha Hegde
Research Scholar
Department of Computer Science
Mangalore University

**Comment by sagorbrur** [comment]
Hi @hegdekasha ,
You have to install fasttext separately by `pip install fasttext==0.9.2`
If you have a Linux-based OS it will work, but I am not sure about Windows or Mac. Last time I got an error in Windows.
This is the reason I made it separate and installable.

**Comment by hegdekasha** [comment]
I am using in Google colab.

**Comment by sagorbrur** [comment]
It will work then. 
Install fasttext by `pip install fasttext==0.9.2` and run your code again.

Cheers

**Comment by hegdekasha** [comment]
Ok thank you.i will check
