### ISSUE TITLE
getting error for  len(bft.model.wv)

### ISSUE THREAD

**Issue by hegdekasha** [sagorbrur/bnlp#39]
Hai,
I wanted get the vocabulary size of BNLPfasttext model. I used similar code which worked for word2vec. However, it is not working for for fastext. could to please help me

**Comment by sagorbrur** [comment]
Hi @hegdekasha ,
Here is the way to get the vocab size: 

```py
from bnlp.embedding.fasttext import BengaliFasttext

bft = BengaliFasttext()

print(len(bft.model.words))
```

You can check the inside module and get other method by the following steps:
```py
from bnlp.embedding.fasttext import BengaliFasttext

bft = BengaliFasttext()
print(dir(bft))
# bft contains a module "model"
# then again you can check the inside module by
print(dir(bft.model))
# now you will get the other module inside bft.model and use accordingly
```

Hope it will help.

Regards

**Comment by hegdekasha** [comment]
Thank you it is working

*Regards*
Asha Hegde
Research Scholar
Department of Computer Science
Mangalore University
