### ISSUE TITLE
Missing parentheses in call to 'print'. Did you mean print(...)?

### ISSUE THREAD

**Issue by sajeeb007** [sagorbrur/bnlp#40]
importing BengaliPOS results in the following error: _**Missing parentheses in call to 'print'. Did you mean print(...)?**_ on Kaggle.

Obviously a version error.

**Comment by sajeeb007** [comment]
Am I missing something here since everything worked fine in my notebook up until Oct

**Comment by sagorbrur** [comment]
Hi @sajeeb007 ,
Check the version and documentation accordingly. I am also guessing it will be a version problem. 
Also if possible please share the error message with the code snippet.

**Comment by sagorbrur** [comment]
I am assuming your problem was solved.
