### ISSUE TITLE
CleanText remove_punctuations() prints corpus.punctuations unneccessarily

### ISSUE THREAD

**Issue by treeDweller98** [sagorbrur/bnlp#41]
Applying CleanText on datasets floods output with garbage. Please remove the print statement on line 61 from `bnlp/bnlp/cleantext/clean.py`.

A temporary solution till then might be to suppress print statements while applying CleanText:
[How to block calls to print?](https://stackoverflow.com/questions/8391411/how-to-block-calls-to-print)

**Comment by sagorbrur** [comment]
Hi @treeDweller98 ,
Thanks for pointing out the problem.
I will remove the print statement but it will be effective on the upcoming version. 
For now, you can use the method you shared.
