### ISSUE TITLE
NLTK dependency

### ISSUE THREAD

**Issue by mbanon** [sagorbrur/bnlp#46]
Hello,
I am using BNLP, and I noticed that it requieres NLTK==3.8.1. Since that version has been reported as containing a vulnerability (https://github.com/advisories/GHSA-cgvx-9447-vcch), a new version (3.8.2) has been released. 
Do you plan to update the BNLP requirement as well, so it depends on the patched version?
Thanks!

**Comment by sagorbrur** [comment]
Hi,
Thanks for notifying me.
I will update BNLP with the new NLTK version and publish it soon.


Kind regards
Sagor Sarker

**Comment by sagorbrur** [comment]
Hi @mbanon ,
New version with updated NLTK has been published. 
https://pypi.org/project/bnlp-toolkit/4.0.2/

Thanks again.

**Comment by mbanon** [comment]
Awesome, @sagorbrur ! Thank you for the superfast fix :)

**Comment by mbanon** [comment]
Hi again @sagorbrur  , apparently the NLTK people removed version 3.8.2 from pypi and now it should be 3.9+ (latest is 3.9.1), as per https://github.com/nltk/nltk/issues/3301

**Comment by sagorbrur** [comment]
Hi @mbanon ,
I will check and update it soon.

**Comment by sagorbrur** [comment]
Hi @mbanon ,
I have removed the version from nltk dependencies as the code-base doesn't have any high-level impact on it.
I'm hoping it will pick the updated version always.

**Comment by mbanon** [comment]
Great, thanks!
